name: washington_lottery_ticket

services:
    project:
        build: .
        image: washington_lth_project
        environment:
            - HF_HOME=/hf
            - HF_DATASETS_CACHE=/hf/datasets
            - HF_HUB_CACHE=/hf/hub
            - HUGGINGFACE_HUB_CACHE=/hf/hub
            - HISTFILE=/var/.bash_history
        env_file: .env
        volumes:
            # If not running on Linux, remove this line
            - /etc/localtime:/etc/localtime:ro
            - ./.bash_history:/var/.bash_history
            - ./hf:/hf
            - ./datasets:/datasets
            - ./models:/lth/models
            - ./evaluation:/lth/evaluation
            - ./LaTeX:/lth/LaTeX
            - ./washLTH:/usr/local/lib/python3.14/site-packages/washLTH
            - ./scripts:/lth/scripts
            - ./:/lth
        deploy:
            resources:
                reservations:
                    devices:
                        -   driver: nvidia
                            count: all
                            capabilities: [ gpu ]
        runtime: nvidia
#        user: 1000:1000

#    vllm:
#        image: vllm/vllm-openai:v0.18.1
#        environment:
#            - HF_HOME=/hf
#            - HF_DATASETS_CACHE=/hf/datasets
#            - HF_HUB_CACHE=/hf/hub
#            - HUGGINGFACE_HUB_CACHE=/hf/hub
#            - HISTFILE=/var/.bash_history
#        env_file: .env
#        command: ["meta-llama/Llama-3.1-8B-Instruct"]
#        volumes:
#            - /etc/localtime:/etc/localtime:ro
#            - ./.bash_history:/var/.bash_history
#            - ./hf:/hf
##            - /media/valence/Seagate:/hf
##            - /mnt/Current/datasets:/datasets
#            - ./:/lth
#            - ./LaTeX:/lth/LaTeX
#            - ./washLTH:/usr/local/lib/python3.14/site-packages/washLTH
#        deploy:
#            resources:
#                reservations:
#                    devices:
#                        -   driver: nvidia
#                            count: all
#                            capabilities: [ gpu ]
#        runtime: nvidia
#        ports:
#            - "8000:8000"


networks: # This exists because of how I have Docker setup through my Firewall, delete this if I forgot to
    default:
        external: true
        name: main_shared_net
